### ISSUE TITLE
Shop data empty and tabs aren't able to be checked

### ISSUE THREAD

**Issue by psully** [xyzz/acquisition#341]
I've been using Acquisition for a while to update poe.trade and help me make sense of my inventory. I decided to just put in a forum shop for the few people who browse the forums and I'm not having much luck. https://www.pathofexile.com/forum/view-thread/1700422

The session ID is correct, the forum thread number is correct, and my poe.trade token is fine as well. However, when I try to update the shop, it's marked as "Empty". When I try to copy data to the clipboard, it's completely empty as well.

The only thing I can possibly think of is that there might be an issue with some tabs that won't allow themselves to be checked. My public tabs aren't checked and Acquisition won't let me check them. One of my non-public tabs is also showing the same behavior, and I don't know why. Could it be related to the fact that they contain items with prices that were filled out in PoE instead of through Acquisition? Tab #6 isn't public, and the items marked with prices are showing (in PoE) that they aren't priced, but Acquisition is showing them as priced anyway.

All of my tabs are marked as [Inherit]

![image of non-public items](http://i.imgur.com/xCcRm4z.jpg)
Non-public items

![image of public items](http://i.imgur.com/BRPMPBW.jpg)
Public items.

Ideas?

**Comment by ericsium** [comment]
Acquisition intentionally ignores in-game priced items when considering what to send to the forum threads, the main reason for this is to avoid issues with what would essentially be duplicate pricing for items.  For example if you had an item listed in a forum thead and then changed the price in game and didn't have acquisition opened the forum thread would be out-of-date with respect to the in-game priced item resulting potentially in a lot of confusing depending on whether customer saw the forum price or the in game price from poe.trade.

With regards to the ability to check tabs - if any item is manually or in-game priced its corresponding tab is 'force' loaded (shaded).  This is to make sure that aquisition has up-to-date info on all possible tabs where pricing activity is occuring.  Some people use the listed by field to keep track of how long either in-game or manually priced items have been listed for.

As far as your 'gems' tabs go - did you price cyclone in-game or using acquisition manually?  If it's priced by acquision you should be able to remove or change the price.  If in-game (based on item note field) you'll be unable to change it from acquisition.

There is subtle 'bug' in aquisition where if you add a note to an item and then change tab from 'public' to 'private' - the note will remain yet item won't be processed by poe.trade or any indexers.  In this case acquistion will incorrectly treat the item as priced because it doesn't currently look at the 'public' or 'private' attribute of the tab.  So I'm guessing you have a note on that item.  Change tab from 'private' back to 'public' and remove note.  Or just move item into your inventory and back to tab to clear the note.

**Comment by psully** [comment]
Thanks for the detailed response. I did move the gems (and other stuff) around to try to solve the problem, but it didn't seem to take. I'll do some more futzing to see if I can wipe those items clean.

Might be worth putting in a FAQ the relationship between in-game pricing and using Acquisition. I feel like I searched everywhere and couldn't find the solution.

**Comment by ericsium** [comment]
Ok, here you go:

https://github.com/xyzz/acquisition/wiki/Pricing-Integration

BTW, items are identified by a hash of attributes (not using new universal ID GGG recently added) so you may be seeing issues related to #258.  Basically if you price an item that has the same attributes as other items *all* items with those attributes will be priced with the same price no matter which tab they are in.

**Comment by psully** [comment]
great. thanks for your help. yeah, the items aren't clearing out that pricing data, no matter what I do.

**Comment by ericsium** [comment]
Can you clarify what you mean when you say 'items aren't clearing out that pricing data' - can we focus on one item that you think has bad pricing data?  I mentioned that if another item in another tab has the same item attributes, all items of that time will be priced with the same amount.  If you're interested in debugging further provide more info on an item - whether you can modify the price in acquistion or not, whether it has an in game 'note' with price set etc...

Else, I'll close this one.

**Comment by psully** [comment]
Sure. I'm noticing a similar issues with another item on a tab that I'd started pricing in Acquisition, where I'd accidentally priced it in-game, but Acquisition doesn't recognize that I'd deleted the price, moved the item back and forth between private and public tabs (and my inventory), and Acquisition won't let me edit the price data. I'll get some screenshots and more details tonight or this weekend (I'm at work now).

**Comment by psully** [comment]
Confirmed there are no other items with the same attributes as these boots:

![Morbid Boots](http://i.imgur.com/cwwBLcw.jpg)

Boots have been moved to personal inventory, back to non-public stash tab, and back to public tab. You can see that the Buyout options are still blanked out, but the pricing data in PoE is blank.

**Comment by psully** [comment]
y'know what... this is a case of user dumb, and probably something else to go in the FAQ. Despite a refresh of the data within Acquisition, GGG's cache of player data is only refreshed every minute or so. So I took the boots out of the stash and let them sit in my inventory for about 5 minutes and refreshed. Then I put them back into the public stash tab and the setting was cleared.

**Comment by ericsium** [comment]
Yeah, it takes some time to update.  Normally zoning will force the update to occur.  Ok, I'll close this.
