### ISSUE TITLE
Auto refresh no longer works

### ISSUE THREAD

**Issue by ssiatkowski** [xyzz/acquisition#397]
After updating from 0.5h to 0.6, the auto refresh feature no longer works. Manually clicking refresh checked tabs works as intended though.

**Comment by ericsium** [comment]
I'm not seeing a problem with auto refresh.  I have 'auto refresh' checked and set interval to 1 minute.  If you click 'event log' in lower right hand corner it prints a message on every refresh.  I'm seeing one every minute.

**Comment by budha2000** [comment]
I have same kind of issue. When its refresh write this: "Received 13 tabs [12 from cache]". And the items what i sold/disappeared from stash dont disappeare from acquisition only after a manual refresh. I tried to change the automate refresh timer but i only get this "Received 13 tabs [12 from cache]" message and nothing happen. For example today after i sold an item 20 mins later it was in the acquisition but the refresh timer was 5 min... About the message what i get. I have with the character 12 tab/cache and acquisition incorrectly numbering it up. The first tab is the "1" but the second is the "3". The last (11) is the "12" + the character so somehow acquisition count with 13 tab instead of 12. I dont know this numbering and the refresh is the same issue or not but maybe...

**Comment by ericsium** [comment]
Auto-refresh only refreshes 'checked' tabs.  If it says 'Received 13 tabs [12 from cache' that means you only have 1 tab checked and that's the only one being auto-refreshed.

**Comment by budha2000** [comment]
But i have 12 tab (with the character) not 13 and all checked. Then how is it possible?

**Comment by ericsium** [comment]
Ok, thanks for details - yeah can confirm this is a bug and auto-refresh is broken.  As you observed all the manual refresh options seem to work fine so you'll have to use that as a workaround until patch.
