### ISSUE TITLE
Network error

### ISSUE THREAD

**Issue by alfanjorfresco** [xyzz/acquisition#512]
cannot loggin

**Comment by OssiPap** [comment]
Doesn't seem to be purely an Acquisition sided problem, Procurement doesn't get through the log in either.

**Comment by alfanjorfresco** [comment]
Network error: Error transferring https://pathofexile.com/login - server replieds: Service Temporarily Unavaible

**Comment by jofabian** [comment]
I'm pretty sure this problem is because they implemented "DDoS protection by Cloudflare".
I get this message when I go to the login page:
"
Checking your browser before accessing pathofexile.com.
This process is automatic. Your browser will redirect to your requested content shortly.

Please allow up to 5 seconds…

DDoS protection by Cloudflare
"

**Comment by DaneelTrevize** [comment]
Duplicate of #510 which has a response from xyzz.
I can also confirm [the error appears like so](https://i.imgur.com/pNDVU3U.png).

**Comment by tutanotaaa** [comment]
Same error since yesterday 

Network error: Error transferring https://pathofexile.com/login - server replied: Service Temporarily Unavaible

**Comment by xyzz** [comment]
As noted above, see #510
