### ISSUE TITLE
Support multiple shop threads

### ISSUE THREAD

**Issue by xyzz** [xyzz/acquisition#55]
The limit is 50000 characters. We should probably allow the user to specify multiple threads separated by comma. Something like that should do it.

**Comment by xyzz** [comment]
Setting the milestone because otherwise the app is basically useless for people with many items to sell.

**Comment by xyzz** [comment]
reopening because it was reverted, see #68

**Comment by goat4dinner** [comment]
Is there coming a version that supports this.. most of my guild has stuck with procurement due to the multiple shops being supported. To be totally honest i love the faster framework of aquisition and hope this feature is top priority as it would make a huge difference in efficiency.

**Comment by goat4dinner** [comment]
anything happening in this area?

**Comment by xyzz** [comment]
Nope, not yet. Maybe after we confirm PoE patch 2.0.0 trading improvements (or lack of them).

**Comment by goat4dinner** [comment]
Haven't we already gotten confirmed there is no such improvement coming? and next patch is still in 2 months away so even if there should be any minor improvements at least you would have the system in place for editing rather than having to start at scratch from that point.

Sry if im persistent but this is a big reason why all people with multiple shops haven't switched yet and your program shows soooo damn much promise i hope this is of the highest priority.

**Comment by kaisongpoe** [comment]
Multiple shops can be set through maybe an additional drop down menu that has an expanded shop thread numbers. Trading improvements were touched upon in chris's guest appearance today, however it sounds like nothing is in any sort of live state ready for release. I run multiple shops out of every league constantly. Just being to run both my HC temp league alongside my SC temp league to update when items are sold would be a huge QoL with the program.

**Comment by xyzz** [comment]
> Just being to run both my HC temp league alongside my SC temp league to update when items are sold would be a huge QoL with the program.

You already can do that by launching multiple instances of Acquisition; this is not what the issue is about.

**Comment by NeverAgain** [comment]
any progress on this ? :(

**Comment by L0m** [comment]
Yeah, this is most waiting feature of acquisition.

**Comment by Gloorf** [comment]
I've been able to (i think) understand the problem here ; there is multiples causes, but the common problem is multiple request overlapping, causing strange behaviour. 
What happen after you log in :
in Application::InitLogin(), ItemsManager::Start() is called, which calls ItemsManagerWorker::Init() (using a connect, but the signal is QThread sending started(), so it's almost instantaneous). After that, Application::InitLogin() also calls ItemsManager::Update(), which emits UpdateSignal(), which triggers ItemsManagerWorker::Update().

It isn't a problem (even if we should probably check for ItemsManager::auto_update_ to launch ItemsManager::Update() in Application::InitLogin() ), since those 2 operations are consecutive. The problem is that they both emit the signal ItemsManagerWorker::ItemRefreshed() who triggers ItemsManager::OnItemRefreshed().

This one calls Shop::ExpireShopData & Shop::SubmitShopToForum(). It forces acquisition to reset the shop data (but this is pretty fast to generate), and sends the data to the forum (which IS slow). 

So at this moment, we have 2 instance of SubmitShopToForum() and 2 requests running approximately at the same time, it can already creates issues.

But it isn't over, as ItemsManager::OnItemRefreshed() also calls Shop::Update(), as long as Shop::auto_update() is true. It also triggers Application::OnItemsRefreshed() who also calls Shop::Update(). It isn't too much a problem (because of the check on "submitting_" at the start), but it's not clean ...

Looking at [the log](https://gist.github.com/Gloorf/ff38edd20c145a3d5657), we can understand it :

> INFO 2015-08-10T02:44:00.404 Updating stash tabs 
ItemsManagerWorker::Update() is called here, so we know that ItemsManagerWorker::Init() is done, which means we have a SubmitShopToForum() running.

>  WARN 2015-08-10T02:44:00.404 Submitting shop right now, the request to update shop data will be ignored 

This happens when Application::OnItemsRefreshed() calls Shop::Update() (which is denied because of SubmitShopToForum() running)

> WARN 2015-08-10T02:44:05.208 Already submitting your shop. 
> WARN 2015-08-10T02:44:05.209 Submitting shop right now, the request to update shop data will be ignored 
> INFO 2015-08-10T02:44:05.583 Finished updating stash. 

Here we know that ItemsManagerWorker::ItemsRefreshed() is emitted because of the last line ; it's displayed in last because in ItemsManagerWorker::OnTabReceived() we first emit, and then display the finished updating stash message.

First line is Shop::SubmitShopToForum() called by ItemsManager::Update() returning an error, because there is still the first SubmitShopToForum() called by ItemsManagerWorker::Init()
Second is Shop::Update() called by Application::OnItemsRefreshed()   returning an error because we have a SubmitShopToForum() running.

> ERROR 2015-08-10T02:44:08.097 Error while submitting shop to forums: Duplicate submission token has expired. Please submit the form again. 

This is just GGG forum saying he doesn't like multiple submission.

In the end, the problem is : 
1) We create a request to GGG forum
2) At the same time, we update the item, so to do that we clean every item
3) When the request checks the items to generate the content, there is no item. So it generates an empty forum thread.
4) Finally, the true request (done after the update of items) with the good content can't go on because of the previous request and GGG doesn't like multiple request.

My suggestion (see [the commit for the actual code](https://github.com/Gloorf/acquisition/commit/a81356a85cb0e59068ce2803d37ab4973c042521), after a couple of tries i'm pretty sure it should resolve the problem) : 
* Don't emit ItemsRefreshed on ItemsManager::Init()
* Don't call Shop::SubmitShopToForum() in ItemsManager::OnItemsRefreshed()
* Instead, call it inside of Shop::Update()

The issue with that is you need at least auto-refresh (because it triggers Shop::Update() from Applications::OnItemsRefreshed()) or auto-update shop (because it triggers Shop::Update()). If you have neither of those, changes a buyout and click "Update shop thread  on forum", you won't call Shop::Update(). This is a minor issue who cans be easily resolved by calling Shop::Update() (if auto-update is off) in onActionUpdate_shop_triggered() : this won't cause a double submission because auto_update beeing off won't call SubmitShopToForum() in Shop::Update().

This is a fairly long post, i've tried to make it as clear as possible because it's kinda complex.

Also, in my understanding i'm not completely sure why we doesn't have this bug in the master branch. It's probably because (ironically) there is no check on the current state (with testing submitting_ or updating_, things like that) that it's allowed to work.

**Comment by NeverAgain** [comment]
@Gloorf thanks for the elaborate explanation. I will check out your codes to see if it's working for me. 

Thanks again

**Comment by xyzz** [comment]
Thanks for investigating this issue. However, with the current proposed patch when starting Acquisition it won't display any items until they're downloaded from the website. Perhaps we could add a different signal or just a parameter to ItemsRefreshed telling whether it's the "initial refresh" (i.e. items loaded from the db) or an actual refresh (from the website). Then we just don't update shop when the items are loaded from the db because it won't make much sense anyway (the shop is likely already updated to have the items we have in the db).

**Comment by Gloorf** [comment]
Yeah, completely forgot about that :) Does [this](https://github.com/Gloorf/acquisition/commit/851a96e08d14742d5b2934123b8aaf8a5733adf0) works for you ? Simply added a parameter to ItemsRefreshed (easier than having to reconnect every slot to a new signal ItemsInitialized)

**Comment by xyzz** [comment]
okay, can you pull request the fixes?

**Comment by Grzanek88** [comment]
Hi, i have problem with multi shop i acquisition 0.5e.
When first thread submit i see this error
"Can't update shop -- cannot extract CSRF token from the page. Check if thread ID is valid. If you're using Steam to login make sure you use the same login method (steam or login/password) in Acquisition, Path of Exile website and Path of Exile game client. For example, if you created a shop thread while using Steam to log into the website and then logged into Acquisition with login/password it will not work. In this case you should either recreate your shop thread or use a correct login method in Acquisition. "
I play with steam and i always login with steam passwords.
Can u help me please?

**Comment by ericsium** [comment]
This is an old, closed, unrelated thread - can you create a new thread for this issue?
