### ISSUE TITLE
Network lag every ~7 seconds

### ISSUE THREAD

**Issue by LukeDemajo** [xyzz/acquisition#56]
With the application open, every 7 seconds or so a sizable ping spike occurs. This is with and without automatic updates enabled. Closing the application stops the spikes, opening it up again resumes the ping spikes.

**Comment by xyzz** [comment]
What's your network setup?

**Comment by LukeDemajo** [comment]
Not sure what you're asking for, but I'm guessing: Wireless connection to a wireless access point, connected via Ethernet cable to my modem.

**Comment by xyzz** [comment]
Yeah, that's what I was asking for, sorry if it was unclear. Hmmm, are your wireless drivers up to date? I'm asking because I remember experiencing similar issue with outdated drivers, it would "lag" every 5-7 seconds or so when something inside Qt related to QNetworkAccessManager tries to read from Windows registry. I'll see if I can reproduce it.

**Comment by LukeDemajo** [comment]
Just updated my AC 7260 drivers, no change.

**Comment by xyzz** [comment]
Qt bug report: https://bugreports.qt.io/browse/QTBUG-40332
Seems that the only workaround is to recompile Qt with `QT_NO_BEARERMANAGEMENT` defined. I'll see if there's an easier way to solve this.

**Comment by xyzz** [comment]
Alright, there seems to be a fairly simple workaround. Can you try deleting `bearer` folder from `C:\Program Files (x86)\Acquisition`?

**Comment by LukeDemajo** [comment]
Yeah, deleting the bearer folder seems to fix the issue. Thanks.

**Comment by xyzz** [comment]
Good! Since this is a pretty critical issue I've released 0.1b that fixes it.
