### ISSUE TITLE
Impossible to make acquisition work

### ISSUE THREAD

**Issue by TarpanRISES** [xyzz/acquisition#81]
Hello there, i am a new player and i have been trying to create a forum shop, sadly it is been imposible to me.
Everytime i log in it shows this problems:
Errors and warnings will be printed here
 WARN 2015-04-16T14:08:31.124 Asked to update a shop with empty thread ID. 
 WARN 2015-04-16T14:08:31.893 Can't extract selected character name from the page 
ERROR 2015-04-16T14:08:32.362 Can't even fetch first tab. Failed to update items. 

I do nto knwo what am i doing wrong. Can you please help me?

**Comment by xyzz** [comment]
Upload `log.txt` from `%localappdata%\acquisition` to https://gist.github.com/ and link it here.

**Comment by LittleEntity** [comment]
Hallo @TarpanRISES ,
have you checked the league settings in the login screen? When you start acquisition you should select your league in the drop down list. For me this is currently the "Hardcore" league. The "Torment/Bloodlines" leagues are still available though these leagues are outdated in POE. If you select a "Torment/Bloodlines" league the same error appears for me. But that is not an issue, because those leagues are not available anyway.

@xyzz please delete those options for the "Torment/Bloodlines" leagues in the option box. Maybe you can find a way to dynamically create these options in the box by scanning the available leagues? Thankyou very much for your effort ^^ can I donate orbs to you?

**Comment by xyzz** [comment]
> Maybe you can find a way to dynamically create these options in the box by scanning the available leagues? 

It used to work until GGG broke their leagues API, see http://api.pathofexile.com/leagues

**Comment by itman1sam** [comment]
<script src="https://gist.github.com/itman1sam/38b9aa236b3b8fd2698b.js"></script>

same problem too

Errors and warnings will be printed here
 WARN 2015-08-08T08:54:37.142 Can't extract selected character name from the page

**Comment by xyzz** [comment]
No reply for >4 months.

**Comment by JCDenis1** [comment]
I have a problem on my work computer with Acquisition. On my home computer everything is fine. But when i'm logining from my work i'm getting this message "Can't even fetch first tab. Failed to update items." and no itmes loaded.
